import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Sidebar from "@/components/sidebar";
import SidebarContents from "@/components/sidebarContents";
// import Link from "next/link";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const FillSidebar = () => {
//   return (
//     <ul>
//       <li>
//         <Link href="/manager/menu" className="text-gray-700 hover:text-blue-500">
//           Menu
//         </Link>
//       </li>
//     </ul>
//   );
// };

export default function ManagerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Sidebar>
          
        </Sidebar>
        <ToastContainer containerId={`toastMenu`} />
        <ToastContainer containerId={`toastUser`} />
        {children}
      </body>
    </html>
  );
}
